### ISSUE TITLE
Rework debos-recipes directories structure

### ISSUE THREAD

**Issue by fdanis-oss** [go-debos/debos-recipes#13]
Current debos-recipes directories structure is not consistent, the directory for Wandboard is located at `debian/armhf/image-wb` while RaspberryPi 3 ones are directly at top-level.
I think it can be better to move all board directories at top level.

By the way, as explained in issue #6 _Support Raspberry Pi 3b Plus_, RapsberryPi 3 recipes can be merged by moving to _buster_.

Some base packages (debootstrap only, minimal and weston) can be added and re-used by the board's recipes using the new 'recipe' action.

The new directory tree could be:
```
debos-recipes/
  |- os/
  |  |- overlays/
  |  |- scripts/
  |  |- debian-base.yaml
  |  |- debian-minimal.yaml
  |  |- debian-weston.yaml
  |- rpi/
  |  |- overlays/
  |  |- scripts/
  |  |- debimage-rpi3.yaml
  |- wandboard
     |- overlays/
     |- scripts/
     |- debimage-wb.yaml
```

debian-base.yaml: Generates an archive of a debootstraped filesystem
```
parameters:
  suite: "stretch", "buster", "sid", ... (debian suite), default is "buster"
  architecture: amd64, armhf, arm64, ..., default is amd64
  ospack: archive name without extension (.tar.gz is automatically added), default is debian-base-<suite>-<architecture>
```

debian-minimal.yaml: Generates an archive of a simple console based debian OS, with simple network support and sshd, user is 'user' (password 'user')
```
parameters:
  suite: "stretch", "buster", "sid", ... (debian suite), default is "buster"
  architecture: amd64, armhf, arm64, ..., default is amd64
  ospack: archive name without extension (.tar.gz is automatically added), default is debian-minimal-<suite>-<architecture>
```

debian-weston.yaml: Generates an archive of a simple graphical based debian OS, with simple network support and sshd, user is 'user' (password 'user'), based on PR #12
```
parameters:
  suite: "stretch", "buster", "sid", ... (debian suite), default is "buster"
  architecture: amd64, armhf, arm64, ..., default is amd64
  ospack: archive name without extension (.tar.gz is automatically added), default is debian-weston-<suite>-<architecture>
```

debimage-rpi3.yaml: Board specific recipe generating the final image, including debian-common-rpi.yaml
```
parameters:
  suite: "stretch", "buster", "sid", ... (debian suite), default is "buster"
  target: "minimal" or "weston", default is "minimal"
  image: final image name, default is debian-rpi-<suite>-<target>-arm64.img
```
